// <auto-generated />
namespace ServiceMate.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initialDbGeneration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialDbGeneration));
        
        string IMigrationMetadata.Id
        {
            get { return "201404130933328_initialDbGeneration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
